layout_bigstreet = """
xxxxxxxxxxx......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.....xxxxxxxxxx.............................xxxx
xxxxxxxxxxxxxxxxx.xx............xxxxxxxxxxxxxxxxxxxxxxxxxxx...xx
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x...
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxx..........xxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxx.........xxxxxx.x...........xxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.......xxxxxxx.xxxxxx.xxxx.xxxxxx...............
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx..xxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxx............................................................
.....xxxxxxxxx..xxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xx.xxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xx..xxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxx.xxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxx..xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx.xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx.xxxxxxx..xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx..xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxx..xxxx..xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxx.xxxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxx..xxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxx.xxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxx.....xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxx.................................xxxxxxxxxxxxxxxx.xxxx
"""

layout_smallstreet = """
xxxxxxxxxxg......xgxgxxxxxxxxxxgxxgxgxgxgxgxgxgxgxgxgxgxgxx.gxxx
xxxxxxxxxxxgxgxx.....xxgxgxgxgx.............................xgxx
xxxxxxxxxxxxxxxxx.xx............xgxgxxgxgxgxgxgxgxgxgxgxgxx...xg
xxxxxxxxxxxxxxxxg.xxsxsxsxsxsxsxxxxxxxxxxxxxxxxxxxxxxxxxxxg.x...
xxxxxgxgxgxgxgxgx.gxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xgxg
xggx..............xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxg.gxxx
g....xgx.xgxgxgx.gxxxxxxxxxxxxgxgxgxgxgxxxxxxxxxxxxxxxxxxxx.xxxx
x.xgxxxg.gxxxxxx.xxxxxgxgxgxgx..........xgxgxgxgxgxxxxxxxxg.gxxx
g..xxxxx.xxxxxxx.ssxgx.........gxgxgx.x...........gxgxgxgxx.xgxg
xx.gxxxg.gxxxxxg.......xx.x.xx.xxxxxx.xxxx.xgxx.x...............
xg.xxxxx.xxxxxxx.xx.xx.xx.x.xx.gxxxxx.gxxx.gxxg.gxxxxss.xxx.xgxg
xx..gxg..gxxxxg..xx.xx......xx.xxxxxx.xxxg.xxxx.xxxxxxx.....gxxx
xxg.xxx.xxxxxxx.xxx....xx.x.xx.gxxxxx.gxxx.gxxg.gxxxxxg.xxx.xxxx
xxx.gx..gxxxxxg.xxx.xx.xx.x.xx.xxxxxx.xxxg.xxxx.xxxxxxx.xxx.gxxx
.x..xg.xxxxxxxx.xxx.xx.........gxxxxx.gxxx.gxxg.gxxxxxg.....xxxx
.x.xgx.xggxggxg.xxx.xx.xx.x.xx.xxxxxx.xgxx.xxgx.xgxgxgx.xxx.gxgx
.g.x............................................................
.x...xgxgxx.xx..xgxgxx.xgxgxgxgxgxgxg.xgxx.sxxx.xxxxx.xgxgx.xgxg
...xgxxxxxx.xx.xxxxxxx.xxgxgxgxgxxxxx.gxxg.sxxx.xxxxx.xxxxg.gxxx
x...xxxxxxx.x..xxxxxx...........gxxxg.xxxx......xxxxx.gxxxx.xxxx
xxx.xxxxxxx.x.xxxxxx..xgxgxgxgx..gxxx.gxxg.x.xx.xxxxx.xxxxg.gxxx
xxx..gxxxxx.x.xx.....xxxxxxxxxxx..gxg.xxxx.x.xx.xxxxx.gxxxx.xxxx
xxxx.xxxxxx...x..xxxxxxxxxxxxxxxg..xx.gxxg.x.xx.xxxxx.xxxxg.gxxx
xxxx.xxxxxxx.xx.sxxxxxxxxxxxxxxxxx..x.xxxx.x.xx.xxxx..gxxxx.xxxx
xxxx..gxxxxx.xx.sxxxxxxxxxxxxxxxxxg...gxxg...........xxxxxg.gxxx
xxxxx.xxxxx............gxxxxxxxxxxxxg.xxxx.xgxx.gxxggxxxxxx.xxxx
xxxxx..xxxx.xxgxgxgxgx.gxxxxxxxxxxxxx.gxxg.xxxg.xxxxxxxxxxg.gxxx
xxxxxx.xxxx.gxxxxxxxxg.xxxxxxxxxxxxxg.xxxx.gxxx.gxxxxxxxxxg.xxxx
xxxxxx..xx..xxxxxxxxxx.gxxxxxxxxxxxxx.gxxg.xxxg.xxxxxxxxxxx.gxxx
xxxxxxx.xx.gxxxxxxxxxg.xxxxxxxxxxxxxg.xxxx.gxxx.gxxxxxxxxxg.xxxx
xxxxxxx....xxgxgxgxgxx.gxggxgxgxgxgxg.gxgx.xxgx.xgxgxggxgxg.gxxx
xxxxxxxxx...................................................xxxx
"""

layout_bongcheonstreet = """
xxxxxxgxgxgxgxgxgxgxgxgxgxgxgxgxgxgxgxgxgxgxxxxxxxxxx
xxx...............................................xxx
xxx...............................................xxx
xxxxsxsxsxsxsxsxsxxxxxsxsxsxsxsxsxsxsxsxsxxxxxxxxxxxx
"""

layout_301 = """
xxxxxxxgxxx
xxxs....gxx
xxxxxxx.xxx
xxxxxxg.gxx
xxxxxxxgxxx
"""

layout_302 = """
xxxxxxxsxxxxxxx
xxs.xxs.gx..gxx
xxxxxxxgxx..gxx
xxs.sxxxxx..gxx
xxxxxxxxxx..gxx
xxs.sxx..x..gxx
xxxsxxx..x..gxx
xxxxxxx..x..gxx
xxxsxxx..x..gxx
xxs.sxx..x..gxx
xxxsxxx..x..gxx
xxxxxxxxxxxxxxx
"""