layout_bixstreet = """
xxxxxxxxxxx......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.....xxxxxxxxxx.............................xxxx
xxxxxxxxxxxxxxxxx.xx............xxxxxxxxxxxxxxxxxxxxxxxxxxx...xx
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x...
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxx..........xxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxx.........xxxxxx.x...........xxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.......xxxxxxx.xxxxxx.xxxx.xxxxxx...............
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx..xxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxx............................................................
.....xxxxxxxxx..xxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xx.xxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xx..xxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxx.xxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxx..xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx.xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx.xxxxxxx..xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx..xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxx..xxxx..xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxx.xxxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxx..xxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxx.xxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxx.....xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxx.................................xxxxxxxxxxxxxxxx.xxxx
"""

layout_smallstreet = """
xxxxxxxxxxx......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.....xxxxxxxxxx.............................xxxx
xxxxxxxxxxxxxxxxx.xx............xxxxxxxggggggggggxxxxxxxxxx...xx
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x...
xxxxxxxggggggxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.sxxx
xxxx..............xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.sxxx
x....xxx.xxxxxxx.xxxxxxxxxxxxxxxgxxxgxxxxxxxxxxxxxxxxxxxxxx.sxxx
x.xxxxxx.xxxxxxx.xxxxxxxxxxxxx..........xxxxxxxxxxxxxxxxxxx.sxxx
x..xxxxx.xxxxxxx.ssxxx.........xxxxxx.x...........xxxxxxxxx.xxxx
xx.xxxxx.xxxxxxx.......xx.x.xx.xxxxxg.xxxx.xxxx.x...............
xx.xxxxx.xxxxxxx.xx.xx.xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxss.xxx.xxxx
xx..xxx..xxxxxx..xx.xx......xx.xxxxxx.xxxx.xxxx.xxxxxxx.....xxxx
xxx.xxx.xxxxxxx.xxx....xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxxx.xxx.xxxx
xxx.xx..xxxxxxx.xxx.xx.xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxxx.xxx.xxxx
.x..xx.xxxxxxxx.xxx.xx.........xxxxxx.xxxx.xxxx.xxxxxxx.....xxxx
.x.xxx.gggggggg.xxx.xx.xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxxx.xxx.xxxx
.x.x............................................................
.x...xxxxxx.xx..xxxxxx.xxxgxxxxgxxxxx.xxxx.sxxx.xxxxx.xxxxx.xxxx
...xxxxxxxx.xx.xxxxxxx.xxxxxxxxxxxxxx.xxxx.sxxx.xxxxx.xxxxx.xxxx
xx..xxxxxxx.x..xxxxxx...........xxxxx.xxxx......xxxxx.xxxxg.sxxx
xxx.xxxxxxx.x.xxxxxx..xxxxxxxxx..xxxx.xxxx.x.xx.xxxxx.xxxxg.sxxx
xxx..xxxxxx.x.xx.....xxxxxxxxxxx..xxx.xxxx.x.xx.xxxxx.xxxxx.sxxx
xxxx.xxxxxx...x..xxxxxxxxxxxxxxxx..xx.xxxx.x.xx.xxxxx.xxxxg.sxxx
xxxx.xxxxxxx.xx.sxxxxxxxxxxxxxxxxx..x.xxxx.x.xx.xxxx..xxxxx.xxxx
xxxx..xxxxxx.xx.sxxxxxxxxxxxxxxxxxx...xxxx...........xxxxxg.xxxx
xxxxx.xxxxx............xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxx.xxxx
xxxxx..xxxx.gxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxg.xxxx
xxxxxx.xxxx.gxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxx.xxxx
xxxxxx..xx..gxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxg.xxxx
xxxxxxx.xx.gxxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxx.xxxx
xxxxxxx....gxxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxg.xxxx
xxxxxxxxxx..................................................xxxx
"""

layout_2way ="""
xxxxxxxxxxxxxxxxxxxxxxd.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxd.lllllllll.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx.rrrrrrrrr.uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxgxxxgxxxd.lllllll.xxxxxxxxxxxxxxxxxxxx.lllllllllllllllllllllllllllllllllllllllllllllllllllllllduxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.rrurrrr.uxxxxxxxxxxxxxxxxxxxxd.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrruxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxd.llllllllllllllllllll.uxxxxxxsxxxxxxgxxxxxxxgxxxxxxxgxxxxxxxxxgxxxxxxxxxxxxxxd.lll.xxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxx.rrrrrrrrrrrrrrrrrrrrrr.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdurr.uxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxsxxxsxxxsxxxsxxxsxxxsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxd.llll
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxgduxx.rrrr.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxgxxxxxxxxxxxxxxxxgxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxx.lllllll.lllllllllllllllll.uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxd.rrrrrrr.rrrrrrrrrrrrrrrur.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxgduxxxxxxxx
xx.lllll.uxxxxxxduxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxgduxxxxxxxx
xxd.rrrrr.xxxxxxduxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxduxxxxxxxxxxxxduxxxxxxxxxxxxxxdusxxxxxxxxxxxxxxxxxxxxxxxxx.lllllllllllll.llll.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxduxxxxxxxxxxxxduxxxxxxxxxxxxxxdusxxxxxxxxxxxxgxxxxxxxxxxxxd.rrrrrrrrrrrrr.rr.uxxxxxxxxxxxxxxxgxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxd.l.xxxxxxxxxxduxxxxxxxxxxxxxxdusxxxxxxxxx.lllllllll.lllllduxxxxxxxxxxxxduxxd.llll.lllllllll.llll.xxxxxxxxxxxxxxxxxxduxxxxxxxx
xx.r.uxxxxxxxxxxduxxxxxxxxxxxxxxdusxxxxxxxxxd.rrrrrurrr.rrrrruxxxxxxxxxxxxduxx.rrrrrr.rrrrrrrrr.rr.uxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxduxxxxxxxxxxduxxxxxxxxxxxxxxdlllll.lllllduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxd.llllllllll.lllllll.lllllllll
xxxxduxxxxxxxxxxduxxxxxxxxxxxxxxdurrrrr.rrrrruxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxx.rrrrrrrrrrrr.rrrrrrr.rrrrrrr.
xxxsduxxxxxxxxxxduxxxxxxxxxxxxxxduxxxxduxxxxduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxsxsxduxxxxxxduxxxxxxxx
xxxsduxxxxxxxxxxduxxxxxxxxxxxxxxduxxxxduxxxxduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxduxxxxxxduxxxxxxxx
xxxsd.l.gxxxxx.l.uxxxxxxxxxxxx.l.uxxxxduxxxxdlllll.lll.uxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxdlllllllduxxxxxxxx
xxxs.r.uxxxxxxd.r.xxxxxxxxxxxxd.r.xxxxduxxxxdurrrrr.rrr.xxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxgduxxxxxxxxxxxxxxdurrrrrrruxxxxxxxx
xxxxxxduxxxxxxduxxxxxxxxxxxxxxduxxxxxxd.llllduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxgduxxxxxxxxxxxxxxduxxxxxxduxxxxxxxx
xxxxxxduxxxxxxduxxxxxxxxxxxxxxduxxxxxx.urrrrruxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxduxxxxxxdugxxxxxxx
xxxxxxduxxxx.l.uxxxxxxxxxxxxxxduxxxxxxduxxxxduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxduxxxxxxduxxxxxxxx
xxxxxxduxxxxd.r.xxxxxxxxxxxxxxduxxxxxxduxxxxduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxduxxxgxxduxxxxxxxx
.l.x.l.uxxxxduxxxxxxxxxxxxxxxxduxxxxxxduxxxxdlllll.lll.llllld.xxxxxxxxxxxxduxxxxxxxxduxxxxxxxgduxxxxxxxxxxxxxxdlllllllduxxxxxxxx
r.uxd.r.xxxxduxxxxxxxxxxxxxxxxduxxxxxxduxxxxdurrrrr.rrr.rrrr.uxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxdurrrrrrruxxxxxxxx
xduxduxxxxxxduxxxxxxxxxxxxxxxxduxxxxxxduxxxxduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxduxxxxxxduxxxxxxxx
xduxduxxxxxxduxxxxxxxxxxxxxxxxduxxxxxxduxxxxduxxxxduxxduxxxxduxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxduxxxxxxduxxxxxxxx
xduxduxx.llldlllllllll.lllllll.lllllll.lllll.lllll.lll.llllldlllllllllllll.lllllllll.lllllllll.lllllllllll.lll.lllllll.lllllllll
xduxduxxd.rrrrrrrrrrrrr.rrrrrrr.rrrrrrr.rrrrr.rrrrr.rrr.rrrrrrrrrrrrrrrrrrr.rrrrrrrrr.rrrrrrrrr.rrrrrrrrrrr.rrr.rrrrrrr.rrrrrrr.
xduxdlll.uxxxxgxxxxxxxduxxxxxxduxxxxxxxxxxxxduxxxxxxxxxgxxxxxxxxxgxxxxxxxxduxxxxxxxxdusxxxxxxxduxxxxxxxxxxduxxxxxxxxxxduxxxxxxxx
xduxdurrr.xxxxxxxxxxxxduxxxx.l.uxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxdusxxxxxxxduxxxxxxxxxxdugxxxxxxxxxduxxxxxxxx
xd.lduxxxxxxxxxxxxxxxxduxxxxd.r.xxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxdusxxxxxxxduxxxxxxxxxxduxxxxxxxxxxduxxxxxxxx
x.rrruxxxxxxxxxxxxxxxxduxxxxduxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxdusxxxxxxxduxxxxxxxxxxduxxxxxxxxxxdugxxxxxxx
xxxxd.l.xxxxxxxxxxxxxxduxx.l.uxxxxxxxxxxxx.l.llllllllllllllllll.xxxxxxxxxxduxxxxxxxxd.ll.lllll.uxxxxxxxxxxduxxxxxxxxxxduxxxxxxxx
xxxx.r.uxxxxxxxxxxxxxxduxxd.r.xxxxxxxxxxxxd.r.rrrrrrrrrrrrrrrr.uxxxxxxxxxxduxxxxxxxx.urrr.rrrrr.xxxxxxxxxgduxxxxxxxxxxduxxxxxxxx
xxxxxsduxxxxxxxxxxxxxgduxxduxxxxxxxxxxxx.l.uxxxxxxxxsxxxxxxxxxd.l.xxxxxxxxduxxxxxxxxduxxduxxxxduxxxxxxxxxxduxxxxxxxxxxduxxxxxxxx
xxxxxsduxxxxxxxxxxxxxxduxxduxxxxxxxxxxxxd.r.xxxxxxxxxxxxxxxxxx.r.uxxxxxxxxduxxxxxxxxduxxduxxxxduxxxxxxxxxxduxxxxxxxxxxduxxxxxxxx
xxxxxsd.l.xxxxxxxxxxxxduxxduxxxx.lllllll.uxxxxxxxxxxxxxxxxxxxxxxd.l.xxxxxxduxxxxxxxxduxxduxxxxduxxxxxxxxxxduxxxxxxxxxgduxxxxxxxx
xxxxxs.r.uxxxxxxxxxxxxduxxduxxxxd.rrrrrrr.xxxxxxxxxxxxxxxxxxxxxx.r.uxxxxxxduxxxxxxxxduxxduxxxxduxxxxxxxxxxdugxxxxxxxxxduxxxxxxxx
xxxxxxxxduxxxxxxxxxxxxd.ll.uxx.l.uxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd.l.xxxxduxxxxxxxxduxxduxxxxduxxxxxxxxxxduxxxxxxxxxxduxxxxxxxx
xxxxxxxxdugxxxxxxxxxxx.rrur.xxd.r.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.r.uxxxxduxxxxxxxxduxxduxxxxduxxxxxxxxxxduxxxxxxxxxxduxxxxxxxx
xxxxxxxxduxxxxxxxxxxxxxxduxxxxdusxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd.l.xxduxxxxxxxxduxxduxxxxduxxxxxxxx.l.uxxxxxxxxxxduxxxxxxxx
xxxxxxxxduxxxxxxxxxxxxxxduxxxxdusxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.r.uxxduxxxxxxxxduxxduxxxxduxxxxxxxxd.r.xxxxxxxxxxduxxxxxxxx
xxxxxxxxd.l.xxxxxxxxxxxxduxxxxdusxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd.llduxxxxxxxgd.ll.lllll.lllllllll.uxxxxxxxxxxxxdugxxxxxxx
xxxxxxxx.r.uxxxxxxxxxxxxduxxxxdusxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.rrrruxxxxxxxx.urrr.rrrrr.rrrrrrrrr.xxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxduxxxxxxxxxx.ldlllll.llllllllllllll.xxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxduxxxxxxxxxxd.rrrrrrr.rrrrrrrrrrrr.uxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxd.l.xxxxxxxxduxxxxgxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxx.r.uxxxxxxxxduxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxgdugxxxxxxxxxxxxxxxxxxxxgduxxxxxxxx
xxxxxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxgduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxgduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxd.l.xxxx.l.uxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxx.r.uxxxxd.r.xxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxduxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxduxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxd.llllduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxx.rrrrrruxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxxduxxxxxxxxduxxxxxxxxxxxxxxxxxxxxxxduxxxxxxxx
xxxxxxxxxxxxxxxxxxxxd.llllllllllllllllllllll.llllllllllllllllllllllllllllldlllllllll.lllllllll.lllllllllllllllllllllll.uxxxxxxxx
xxxxxxxxxxxxxxxxxxxx.rrrrrrrrrrrrrrrrrrrrrrrr.rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.rrrrrrrrr.rrrrrrrrrrrrrrrrrrrrrrr.xxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
"""

layout_2way_simple ="""
xxxxxxxxd.xxxx
xxgxxxxxduxsxx
.lllllll.lllll
rrrrrrrrr.rrr.
xsgxgxxxduxxsx
xxxxx.ll.uxxxx
xxxxxd.rr.xxxx
xxxxgduxxgxxxx
xxxxg.uxxxxxxx
"""



layout_bonxcheonstreet = """
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxx...............................................xxx
xxx...............................................xxx
xxxxsxsxsxsxsxsxsxxxxxsxsxsxsxsxsxsxsxsxsxxxxxxxxxxxx
"""

layout_301 = """
xxxxxxxxxxx
xxxs....xxx
xxxxxxx.xxx
xxxxxxx.xxx
xxxxxxxxxxx
"""

layout_302 = """
xxxxxxxsxxxxxxx
xxs.xxs.xx..xxx
xxxxxxxxxx..xxx
xxs.sxxxxx..xxx
xxxxxxxxxx..xxx
xxs.sxx..x..xxx
xxxsxxx..x..xxx
xxxxxxx..x..xxx
xxxsxxx..x..xxx
xxs.sxx..x..xxx
xxxsxxx..x..xxx
xxxxxxxxxxxxxxx
"""
