layout_bixstreet = """
xxxxxxxxxxx......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.....xxxxxxxxxx.............................xxxx
xxxxxxxxxxxxxxxxx.xx............xxxxxxxxxxxxxxxxxxxxxxxxxxx...xx
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x...
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxx..........xxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.xxxxx.........xxxxxx.x...........xxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.......xxxxxxx.xxxxxx.xxxx.xxxxxx...............
xxxxxxxxxxxxxxxx.xxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx..xxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxxxxxxxxxxxxx.xxxxxxxxxxxxxx.xxxxxx.xxxx.xxxxxxxxxxxx.xxx.xxxx
xxxx............................................................
.....xxxxxxxxx..xxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xx.xxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xx..xxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxx.xxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxx..xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx.xxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx.xxxxxxx..xxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxx..xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxx..xxxx..xxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxx.xxxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxx..xxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxx.xxx.xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxx.....xxxxxxxxxxxxxxxxxxxxxxxxx.xxxx.xxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxx.................................xxxxxxxxxxxxxxxx.xxxx
"""

layout_smallstreet = """
xxxxxxxxxxx......xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxx
xxxxxxxxxxxxxxxx.....xxxxxxxxxx.............................xxxx
xxxxxxxxxxxxxxxxx.xx............xxxxxxxggggggggggxxxxxxxxxx...xx
xxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x...
xxxxxxxggggggxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.sxxx
xxxx..............xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.sxxx
x....xxx.xxxxxxx.xxxxxxxxxxxxxxxgxxxgxxxxxxxxxxxxxxxxxxxxxx.sxxx
x.xxxxxx.xxxxxxx.xxxxxxxxxxxxx..........xxxxxxxxxxxxxxxxxxx.sxxx
x..xxxxx.xxxxxxx.ssxxx.........xxxxxx.x...........xxxxxxxxx.xxxx
xx.xxxxx.xxxxxxx.......xx.x.xx.xxxxxg.xxxx.xxxx.x...............
xx.xxxxx.xxxxxxx.xx.xx.xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxss.xxx.xxxx
xx..xxx..xxxxxx..xx.xx......xx.xxxxxx.xxxx.xxxx.xxxxxxx.....xxxx
xxx.xxx.xxxxxxx.xxx....xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxxx.xxx.xxxx
xxx.xx..xxxxxxx.xxx.xx.xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxxx.xxx.xxxx
.x..xx.xxxxxxxx.xxx.xx.........xxxxxx.xxxx.xxxx.xxxxxxx.....xxxx
.x.xxx.gggggggg.xxx.xx.xx.x.xx.xxxxxx.xxxx.xxxx.xxxxxxx.xxx.xxxx
.x.x............................................................
.x...xxxxxx.xx..xxxxxx.xxxgxxxxgxxxxx.xxxx.sxxx.xxxxx.xxxxx.xxxx
...xxxxxxxx.xx.xxxxxxx.xxxxxxxxxxxxxx.xxxx.sxxx.xxxxx.xxxxx.xxxx
xx..xxxxxxx.x..xxxxxx...........xxxxx.xxxx......xxxxx.xxxxg.sxxx
xxx.xxxxxxx.x.xxxxxx..xxxxxxxxx..xxxx.xxxx.x.xx.xxxxx.xxxxg.sxxx
xxx..xxxxxx.x.xx.....xxxxxxxxxxx..xxx.xxxx.x.xx.xxxxx.xxxxx.sxxx
xxxx.xxxxxx...x..xxxxxxxxxxxxxxxx..xx.xxxx.x.xx.xxxxx.xxxxg.sxxx
xxxx.xxxxxxx.xx.sxxxxxxxxxxxxxxxxx..x.xxxx.x.xx.xxxx..xxxxx.xxxx
xxxx..xxxxxx.xx.sxxxxxxxxxxxxxxxxxx...xxxx...........xxxxxg.xxxx
xxxxx.xxxxx............xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxx.xxxx
xxxxx..xxxx.gxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxg.xxxx
xxxxxx.xxxx.gxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxx.xxxx
xxxxxx..xx..gxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxg.xxxx
xxxxxxx.xx.gxxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxx.xxxx
xxxxxxx....gxxxxxxxxxx.xxxxxxxxxxxxxg.xxxx.xxxx.xxxxxxxxxxg.xxxx
xxxxxxxxxx..................................................xxxx
"""

layout_2way ="""
xxxxxxxxxxxxxxxxxxxxxx++++++++++++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx-----------+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+..++++++xxxxxxxxxxxxxxxxxxxx++++++++++++++++++++++++++++++++++++++++++++++++++++++++..xxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--..-----+xxxxxxxxxxxxxxxxxxxx+-------------------------------------------------------..xxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.+xxxx-++++++++++++++++++++++-xxxxxxsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..++++xxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.+xxxx------------------------xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..---+xxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.+xxxxsxxxsxxxsxxxsxxxsxxxsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xx-+++++
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxg-+xx------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxgxxxxxxxxxxxxxxxxgxxxxxxxx.+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxx...........................+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxx.+++++++..................++xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxg-+xxxxxxxx
xx........xxxxxx..xxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxg-+xxxxxxxx
xx........xxxxxx..xxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxsxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xx..xxxxxxxxxxxx..xxxxxxxxxxxxxx..sxxxxxxxxxxxxxxxxxxxxxxxxx....................xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xx..xxxxxxxxxxxx..xxxxxxxxxxxxxx..sxxxxxxxxxxxxgxxxxxxxxxxxx....................xxxxxxxxxxxxxxxgxxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xx....xxxxxxxxxx..xxxxxxxxxxxxxx..sxxxxxxxxx..................xxxxxxxxxxxx..xx......................xxxxxxxxxxxxxxxxxx-+xxxxxxxx
xx....xxxxxxxxxx..xxxxxxxxxxxxxx..sxxxxxxxxx..................xxxxxxxxxxxx..xx......................xxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxx..xxxxxxxxxx..xxxxxxxxxxxxxx..............xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xx..++++++++++++++++++..++++++++
xxxx..xxxxxxxxxx..xxxxxxxxxxxxxx..............xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xx..------------------..--------
xxxs..xxxxxxxxxx..xxxxxxxxxxxxxx..xxxx..xxxx..xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxsxsx..xxxxxx-+xxxxxxxx
xxxs..xxxxxxxxxx..xxxxxxxxxxxxxx..xxxx..xxxx..xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx..xxxxxx-+xxxxxxxx
xxxs....gxxxxx....xxxxxxxxxxxx....xxxx..xxxx............xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx........-+xxxxxxxx
xxxs....xxxxxx....xxxxxxxxxxxx....xxxx..xxxx............xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxg..xxxxxxxxxxxxxx........-+xxxxxxxx
xxxxxx..xxxxxx..xxxxxxxxxxxxxx..xxxxxx........xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxg..xxxxxxxxxxxxxx..xxxxxx-+xxxxxxxx
xxxxxx..xxxxxx..xxxxxxxxxxxxxx..xxxxxx........xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx..xxxxxx-+gxxxxxxx
xxxxxx..xxxx....xxxxxxxxxxxxxx..xxxxxx..xxxx..xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx..xxxxxx-+xxxxxxxx
xxxxxx..xxxx....xxxxxxxxxxxxxx..xxxxxx..xxxx..xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx..xxxgxx-+xxxxxxxx
..xx....xxxx..xxxxxxxxxxxxxxxx..xxxxxx..xxxx..................xxxxxxxxxxxx..xxxxxxxx..xxxxxxxg..xxxxxxxxxxxxxx........-+xxxxxxxx
..xx....xxxx..xxxxxxxxxxxxxxxx..xxxxxx..xxxx..................xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx........-+xxxxxxxx
..xx..xxxxxx..xxxxxxxxxxxxxxxx..xxxxxx..xxxx..xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx..xxxxxx-+xxxxxxxx
..xx..xxxxxx..xxxxxxxxxxxxxxxx..xxxxxx..xxxx..xxxx..xx..xxxx..xxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxx..xxxxxx-+xxxxxxxx
..xx..xx++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..xx..xx------------------------------------------------------------------------------------------------------------------------
..xx......xxxxgxxxxxxx..xxxx....xxxxxxxxxxxx..xxxxxxxxxgxxxxxxxxxgxxxxxxxx..xxxxxxxx..sxxxxxxx..xxxxxxxxxx..xxxxxxxxxx-+xxxxxxxx
..xx......xxxxxxxxxxxx..xxxx....xxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..sxxxxxxx..xxxxxxxxxx..gxxxxxxxxx-+xxxxxxxx
......xxxxxxxxxxxxxxxx..xxxx..xxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..sxxxxxxx..xxxxxxxxxx..xxxxxxxxxx-+xxxxxxxx
......xxxxxxxxxxxxxxxx..xxxx..xxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..sxxxxxxx..xxxxxxxxxx..xxxxxxxxxx-+gxxxxxxx
xx......xxxxxxxxxxxxxx..xx....xxxxxxxxxxxx......................xxxxxxxxxx..xxxxxxxx............xxxxxxxxxx..xxxxxxxxxx-+xxxxxxxx
xx......xxxxxxxxxxxxxx..xx....xxxxxxxxxxxx......................xxxxxxxxxx..xxxxxxxx............xxxxxxxxxg..xxxxxxxxxx-+xxxxxxxx
xxxxxs..xxxxxxxxxxxxxg..xx..xxxxxxxxxxxx....xxxxxxxxsxxxxxxxxx....xxxxxxxx..xxxxxxxx..xx..xxxx..xxxxxxxxxx..xxxxxxxxxx-+xxxxxxxx
xxxxxs..xxxxxxxxxxxxxx..xx..xxxxxxxxxxxx....xxxxxxxxxxxxxxxxxx....xxxxxxxx..xxxxxxxx..xx..xxxx..xxxxxxxxxx..xxxxxxxxxx-+xxxxxxxx
xxxxxs....xxxxxxxxxxxx..xx..xxxx..........xxxxxxxxxxxxxxxxxxxxxx....xxxxxx..xxxxxxxx..xx..xxxx..xxxxxxxxxx..xxxxxxxxxg-+xxxxxxxx
xxxxxs....xxxxxxxxxxxx..xx..xxxx..........xxxxxxxxxxxxxxxxxxxxxx....xxxxxx..xxxxxxxx..xx..xxxx..xxxxxxxxxx..gxxxxxxxxx-+xxxxxxxx
xxxxxxxx..xxxxxxxxxxxx......xx....xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx....xxxx..xxxxxxxx..xx..xxxx..xxxxxxxxxx..xxxxxxxxxx-+xxxxxxxx
xxxxxxxx..gxxxxxxxxxxx......xx....xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx....xxxx..xxxxxxxx..xx..xxxx..xxxxxxxxxx..xxxxxxxxxx-+xxxxxxxx
xxxxxxxx..xxxxxxxxxxxxxx..xxxx..sxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx....xx..xxxxxxxx..xx..xxxx..xxxxxxxx....xxxxxxxxxx-+xxxxxxxx
xxxxxxxx..xxxxxxxxxxxxxx..xxxx..sxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx....xx..xxxxxxxx..xx..xxxx..xxxxxxxx....xxxxxxxxxx-+xxxxxxxx
xxxxxxxx....xxxxxxxxxxxx..xxxx..sxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx......xxxxxxxg......................xxxxxxxxxxxx-+gxxxxxxx
xxxxxxxx....xxxxxxxxxxxx..xxxx..sxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx......xxxxxxxx......................xxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxx..xxxxxxxxxx........................xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxx..xxxxxxxxxx........................xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxx....xxxxxxxx..xxxxgxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxx....xxxxxxxx..xxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxg..gxxxxxxxxxxxxxxxxxxxxg-+xxxxxxxx
xxxxxxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxg..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxg..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxx....xxxx....xxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxx....xxxx....xxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxxxx..xxxx..xxxxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxxxx..xxxx..xxxxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxxxx........xxxxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxxxx........xxxxxxxxxxxxxxxxxxxxxx..xxxxxxxxxxxxxxxxxxxxxxxxxxxx..xxxxxxxx..xxxxxxxx..xxxxxxxxxxxxxxxxxxxxxx-+xxxxxxxx
xxxxxxxxxxxxxxxxxx....------------------------------------------------------------------------------------------------..xxxxxxxx
xxxxxxxxxxxxxxxxxx++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++..xxxxxxxx
"""

layout_2way_simple ="""
xxxxxxxxduxxxx
xxgxgxxxduxxgx
llllllll..llll
rrrrrrrr..rrrr
xxgxgxxxduxxxx
xxxxxxxsdusxxx
xxxxxxxxduxxxx
xxxxxxxgduxxxx
"""



layout_bonxcheonstreet = """
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxx...............................................xxx
xxx...............................................xxx
xxxxsxsxsxsxsxsxsxxxxxsxsxsxsxsxsxsxsxsxsxxxxxxxxxxxx
"""

layout_301 = """
xxxxxxxxxxx
xxxs....xxx
xxxxxxx.xxx
xxxxxxx.xxx
xxxxxxxxxxx
"""

layout_302 = """
xxxxxxxsxxxxxxx
xxs.xxs.xx..xxx
xxxxxxxxxx..xxx
xxs.sxxxxx..xxx
xxxxxxxxxx..xxx
xxs.sxx..x..xxx
xxxsxxx..x..xxx
xxxxxxx..x..xxx
xxxsxxx..x..xxx
xxs.sxx..x..xxx
xxxsxxx..x..xxx
xxxxxxxxxxxxxxx
"""
